/**
 * REST API documentation
 * Developed By CSIRT team
 *
 * OpenAPI spec version: 1.0.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { AbstractLevelDTO } from '../abstract-level-dto';

/**
 * Info Level to update.
 */
export interface InfoLevelUpdateDTO {
  id?: number;
  title?: string;
  level_type?: AbstractLevelDTO.LevelTypeEnum;
  content?: string;
}

export class InfoLevelUpdateDTOClass implements InfoLevelUpdateDTO {
  id: number;
  title: string;
  level_type: AbstractLevelDTO.LevelTypeEnum = 'INFO_LEVEL';
  content: string;
}
